### ISSUE TITLE
Uncaught reference error: module is not defined

### ISSUE THREAD

**Issue by bdharrington7** [Xuanwo/nodebb-plugin-html5videoplayer#1]
I'm getting a module undefined error in the client side (minified) javascript when this plugin is active.

Looking at the prettified version of the file, it looks like all of the other client-side scripts start off as 

```
"use strict";
define("plugin/emoji-extended/detection/markdown", function() {
```

with no module passed in as an argument to the IIFE

**Comment by Xuanwo** [comment]
I got it, I will try fix it.

**Comment by Xuanwo** [comment]
Finally, it was fixed, thank you very much.

**Comment by bdharrington7** [comment]
Hm, I activated this plugin and it doesn't seem to work at all now, none of my videos get parsed into a player

**Comment by bdharrington7** [comment]
What's even stranger is, now I get this (after the console log saying video has started):
`Uncaught ReferenceError: hljs is not defined` (from a file called highlight.js)
It only happens when this plugin is loaded, and in a thread
